package com.skyline.pojo;

// Generated 2015-8-31 9:24:24 by Hibernate Tools 4.3.1

/**
 * Email generated by hbm2java
 */
public class Email extends GenericEmail implements java.io.Serializable {

	private String attacheFullName;
	private String resourcePath;
	
	public String getAttacheFullName() {
		return this.attacheFullName;
	}

	public void setAttacheFullName(String attacheFullName) {
		this.attacheFullName = attacheFullName;
	}

	public String getResourcePath() {
		return this.resourcePath;
	}

	public void setResourcePath(String resourcePath) {
		this.resourcePath = resourcePath;
	}

}
