package com.skyline.pojo;

import com.predisw.annotation.Description;

// Generated 2015-8-31 9:24:24 by Hibernate Tools 4.3.1

/**
 * Employee generated by hbm2java
 */
@Description(name="业务员")
public class Employee implements java.io.Serializable {

	private Integer EId;
	private Integer version;
	private String ENum;
	private String ENameEn;
	private String ENameCn;
	private Integer DId;
	private String ETitle;
	private Boolean EStatus;
	private Integer count;
	private Boolean isOften;
	private String email;

	public Employee() {
	}

	public Employee(String ENum, String ENameEn, String ENameCn, Integer DId,
			String ETitle, Boolean EStatus, Integer count, Boolean isOften,
			String email) {
		this.ENum = ENum;
		this.ENameEn = ENameEn;
		this.ENameCn = ENameCn;
		this.DId = DId;
		this.ETitle = ETitle;
		this.EStatus = EStatus;
		this.count = count;
		this.isOften = isOften;
		this.email = email;
	}

	public Integer getEId() {
		return this.EId;
	}

	public void setEId(Integer EId) {
		this.EId = EId;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getENum() {
		return this.ENum;
	}

	public void setENum(String ENum) {
		this.ENum = ENum;
	}

	public String getENameEn() {
		return this.ENameEn;
	}

	public void setENameEn(String ENameEn) {
		this.ENameEn = ENameEn;
	}

	public String getENameCn() {
		return this.ENameCn;
	}

	public void setENameCn(String ENameCn) {
		this.ENameCn = ENameCn;
	}

	public Integer getDId() {
		return this.DId;
	}

	public void setDId(Integer DId) {
		this.DId = DId;
	}

	public String getETitle() {
		return this.ETitle;
	}

	public void setETitle(String ETitle) {
		this.ETitle = ETitle;
	}

	public Boolean getEStatus() {
		return this.EStatus;
	}

	public void setEStatus(Boolean EStatus) {
		this.EStatus = EStatus;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Boolean getIsOften() {
		return this.isOften;
	}

	public void setIsOften(Boolean isOften) {
		this.isOften = isOften;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	public String forLog(){
		return "工号:"+this.getENum();
	}
}
