package com.skyline.pojo;

// Generated 2015-11-4 17:24:19 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Powers generated by hbm2java
 */
public class Powers implements java.io.Serializable {

	private Integer id;
	private String name;
	private String url;
	private Integer parentId;
	private Set roles = new HashSet(0);

	public Powers() {
	}

	public Powers(String name, String url, Integer parentId, Set roles) {
		this.name = name;
		this.url = url;
		this.parentId = parentId;
		this.roles = roles;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Set getRoles() {
		return this.roles;
	}

	public void setRoles(Set roles) {
		this.roles = roles;
	}

}
