package com.skyline.pojo;

// Generated 2015-8-31 9:24:24 by Hibernate Tools 4.3.1

/**
 * Props generated by hbm2java
 */
public class Props implements java.io.Serializable {

	private Integer id;
	private Integer version;
	private String name;
	private String value;

	public Props() {
	}

	public Props(String name, String value) {
		this.name = name;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}



}
