package com.skyline.pojo;

// Generated 2015-11-4 17:24:19 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set powerses = new HashSet(0);
	private Set users = new HashSet(0);

	public Role() {
	}
	
	public Role(String name){
		this.name=name;
	}

	public Role(String name, Set powerses, Set users) {
		this.name = name;
		this.powerses = powerses;
		this.users = users;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getPowerses() {
		return this.powerses;
	}

	public void setPowerses(Set powerses) {
		this.powerses = powerses;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
