package com.skyline.pojo;

// Generated 2015-11-4 17:24:19 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.predisw.annotation.Description;

/**
 * User generated by hbm2java
 */
@Description(name="用户")
public class User implements java.io.Serializable {

	private Integer UId;
	private Integer version;
	private String UName;
	private String password;
	private Date createTime;
	private Date modifiedTime;
	private Set roles = new HashSet(0);

	public User() {
		createTime=new Date();
	}

	public User(String UName, String password, Set roles) {
		this.UName = UName;
		this.password = password;
		this.roles = roles;
	}

	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getUName() {
		return this.UName;
	}

	public void setUName(String UName) {
		this.UName = UName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getRoles() {
		return this.roles;
	}

	public void setRoles(Set roles) {
		this.roles = roles;
	}

	public String forLog(){
		return "用户名:"+this.UName;
	}

	/**
	 * @return the createTime
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the modifiedTime
	 */
	public Date getModifiedTime() {
		return modifiedTime;
	}

	/**
	 * @param modifiedTime the modifiedTime to set
	 */
	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

}
