package com.skyline.pojo;

import com.predisw.annotation.Description;



// Generated 2015-8-11 10:01:01 by Hibernate Tools 4.3.1

/**
 * CountryCode generated by hbm2java
 */
@Description(name="地区详情")
public class CountryCode implements java.io.Serializable {

	private Integer ccId;
	private Integer version;
	private String country;
	private String CCode;
	private String operator;
	private String code;
	private Boolean ctyOften;
	private Integer codeCount;

	public CountryCode() {
	}

	public CountryCode(String country, String CCode, String operator,
			String code, Boolean ctyOften, Integer codeCount) {
		this.country = country;
		this.CCode = CCode;
		this.operator = operator;
		this.code = code;
		this.ctyOften = ctyOften;
		this.codeCount = codeCount;
	}

	public Integer getCcId() {
		return this.ccId;
	}

	public void setCcId(Integer ccId) {
		this.ccId = ccId;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCCode() {
		return this.CCode;
	}

	public void setCCode(String CCode) {
		this.CCode = CCode;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Boolean getCtyOften() {
		return this.ctyOften;
	}

	public void setCtyOften(Boolean ctyOften) {
		this.ctyOften = ctyOften;
	}

	public Integer getCodeCount() {
		return this.codeCount;
	}

	public void setCodeCount(Integer codeCount) {
		this.codeCount = codeCount;
	}
	@Override
	public boolean equals(Object obj) {
		// TODO Auto-generated method stub
		if(obj instanceof CountryCode){
			return this.ccId.equals( ((CountryCode)obj ).ccId);  //用== 不行，有些还是不相等，改用equal 就ok
		}
		return super.equals(obj);
	}
	
	public String getNameForLog(){
		return this.code;
	}
}