package com.skyline.pojo;

// Generated 2015-8-31 9:24:24 by Hibernate Tools 4.3.1

/**
 * Email generated by hbm2java
 */
public class Email implements java.io.Serializable {

	private Integer id;
	private String name;
	private String subject;
	private String content;
	private String addrList;
	private String ccAdddrList;
	private String bccAddrList;
	private String attacheName;
	private String attacheFullName;
	private String resourcePath;

	public Email() {
	}

	public Email(String name, String subject, String content, String addrList,
			String ccAdddrList, String bccAddrList, String attacheName,
			String attacheFullName, String resourcePath) {
		this.name = name;
		this.subject = subject;
		this.content = content;
		this.addrList = addrList;
		this.ccAdddrList = ccAdddrList;
		this.bccAddrList = bccAddrList;
		this.attacheName = attacheName;
		this.attacheFullName = attacheFullName;
		this.resourcePath = resourcePath;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getAddrList() {
		return this.addrList;
	}

	public void setAddrList(String addrList) {
		this.addrList = addrList;
	}

	public String getCcAdddrList() {
		return this.ccAdddrList;
	}

	public void setCcAdddrList(String ccAdddrList) {
		this.ccAdddrList = ccAdddrList;
	}

	public String getBccAddrList() {
		return this.bccAddrList;
	}

	public void setBccAddrList(String bccAddrList) {
		this.bccAddrList = bccAddrList;
	}

	public String getAttacheName() {
		return this.attacheName;
	}

	public void setAttacheName(String attacheName) {
		this.attacheName = attacheName;
	}

	public String getAttacheFullName() {
		return this.attacheFullName;
	}

	public void setAttacheFullName(String attacheFullName) {
		this.attacheFullName = attacheFullName;
	}

	public String getResourcePath() {
		return this.resourcePath;
	}

	public void setResourcePath(String resourcePath) {
		this.resourcePath = resourcePath;
	}

}
