package com.skyline.pojo;

// Generated 2015-8-31 9:24:24 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log implements java.io.Serializable {

	private Integer LId;
	private String ENum;
	private String LType;
	private String LObject;
	private Date LTime;
	private String loContent;
	private String lnContent;

	public Log() {
	}

	public Log(String ENum, String LType, String LObject, Date LTime,
			String loContent, String lnContent) {
		this.ENum = ENum;
		this.LType = LType;
		this.LObject = LObject;
		this.LTime = LTime;
		this.loContent = loContent;
		this.lnContent = lnContent;
	}

	public Integer getLId() {
		return this.LId;
	}

	public void setLId(Integer LId) {
		this.LId = LId;
	}

	public String getENum() {
		return this.ENum;
	}

	public void setENum(String ENum) {
		this.ENum = ENum;
	}

	public String getLType() {
		return this.LType;
	}

	public void setLType(String LType) {
		this.LType = LType;
	}

	public String getLObject() {
		return this.LObject;
	}

	public void setLObject(String LObject) {
		this.LObject = LObject;
	}

	public Date getLTime() {
		return this.LTime;
	}

	public void setLTime(Date LTime) {
		this.LTime = LTime;
	}

	public String getLoContent() {
		return this.loContent;
	}

	public void setLoContent(String loContent) {
		this.loContent = loContent;
	}

	public String getLnContent() {
		return this.lnContent;
	}

	public void setLnContent(String lnContent) {
		this.lnContent = lnContent;
	}

}
