package com.skyline.pojo;

// Generated 2015-8-31 9:24:24 by Hibernate Tools 4.3.1

import java.util.Date;

import com.predisw.annotation.Description;

/**
 * SendRecord generated by hbm2java
 */
@Description(name="发送报价记录")
public class SendRecord implements java.io.Serializable ,Cloneable  {

	private Integer id;
	private String rateName;
	private String vosId;
	private Integer CId;
	private Date sendTime;
	private Integer sendStatus;
	private String UName;
	private Boolean reSendStatus;
	private String excelTp;
	private Boolean isCorrect;
	private Boolean cmtAttach;
	private Boolean cmtSubject;
	private Boolean cmtContent;
	private String emailName;

	public SendRecord() {
	}

	public SendRecord(String rateName, String vosId, Integer CId,
			Date sendTime, Integer sendStatus, String UName,
			Boolean reSendStatus, String excelTp, Boolean isCorrect,
			Boolean cmtAttach, Boolean cmtSubject, Boolean cmtContent,
			String emailName) {
		this.rateName = rateName;
		this.vosId = vosId;
		this.CId = CId;
		this.sendTime = sendTime;
		this.sendStatus = sendStatus;
		this.UName = UName;
		this.reSendStatus = reSendStatus;
		this.excelTp = excelTp;
		this.isCorrect = isCorrect;
		this.cmtAttach = cmtAttach;
		this.cmtSubject = cmtSubject;
		this.cmtContent = cmtContent;
		this.emailName = emailName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRateName() {
		return this.rateName;
	}

	public void setRateName(String rateName) {
		this.rateName = rateName;
	}

	public String getVosId() {
		return this.vosId;
	}

	public void setVosId(String vosId) {
		this.vosId = vosId;
	}

	public Integer getCId() {
		return this.CId;
	}

	public void setCId(Integer CId) {
		this.CId = CId;
	}

	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	public Integer getSendStatus() {
		return this.sendStatus;
	}

	public void setSendStatus(Integer sendStatus) {
		this.sendStatus = sendStatus;
	}

	public String getUName() {
		return this.UName;
	}

	public void setUName(String UName) {
		this.UName = UName;
	}

	public Boolean getReSendStatus() {
		return this.reSendStatus;
	}

	public void setReSendStatus(Boolean reSendStatus) {
		this.reSendStatus = reSendStatus;
	}

	public String getExcelTp() {
		return this.excelTp;
	}

	public void setExcelTp(String excelTp) {
		this.excelTp = excelTp;
	}

	public Boolean getIsCorrect() {
		return this.isCorrect;
	}

	public void setIsCorrect(Boolean isCorrect) {
		this.isCorrect = isCorrect;
	}

	public Boolean getCmtAttach() {
		return this.cmtAttach;
	}

	public void setCmtAttach(Boolean cmtAttach) {
		this.cmtAttach = cmtAttach;
	}

	public Boolean getCmtSubject() {
		return this.cmtSubject;
	}

	public void setCmtSubject(Boolean cmtSubject) {
		this.cmtSubject = cmtSubject;
	}

	public Boolean getCmtContent() {
		return this.cmtContent;
	}

	public void setCmtContent(Boolean cmtContent) {
		this.cmtContent = cmtContent;
	}

	public String getEmailName() {
		return this.emailName;
	}

	public void setEmailName(String emailName) {
		this.emailName = emailName;
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return super.clone();
	}
	
	public String forLog(){
		return "记录ID: "+this.id;
	}
}
