package com.skyline.pojo;

import com.predisw.annotation.Description;

// Generated 2015-8-31 9:24:24 by Hibernate Tools 4.3.1

/**
 * User generated by hbm2java
 */
@Description(name="用户")
public class User implements java.io.Serializable {

	private Integer UId;
	private Integer version;
	private String UName;
	private String password;

	public User() {
	}

	public User(String UName, String password) {
		this.UName = UName;
		this.password = password;
	}

	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getUName() {
		return this.UName;
	}

	public void setUName(String UName) {
		this.UName = UName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String forLog(){
		return "用户名:"+this.UName;
	}
}
